### PR TITLE
Fixed warnings bumped stack

### PR DESCRIPTION
**Pull request by flip111**

### CODE REVIEW

**Review by snoyberg — COMMENTED** [review]
-1. This removes an instance, causing a major version bump, just to remove a compile time deprecation warning.

**Comment by flip111** [comment]
@snoyberg can you include this patch when the time comes if you have more pressing reasons to do a major version bump?

**Comment by snoyberg** [comment]
I'll consider it. Removing these instances doesn't seem to be helpful to anyone, so I'm not following the motivation.

**Comment by flip111** [comment]
They are giving warnings (because of depreciation) during compilation of other packages that depend on monad-logger. Maybe there is a way to silent the warnings with ghc options pragma for your package only if you like to keep Error instead of Except

**Comment by snoyberg** [comment]
You could send a PR to use `OPTIONS_GHC` pragmas to disable the deprecated warnings.

**Comment by flip111** [comment]
ok new PR is here https://github.com/snoyberg/monad-logger/pull/17

**Pull request merged**
