### PR TITLE
Add MonadAccum instances

### PR DESCRIPTION
**Pull request by Futarimiti**
Make `LoggingT` and `NoLoggingT` an instance of `MonadAccum`

### CODE REVIEW

**Comment by Futarimiti** [comment]
Hmm I was unaware of versioning. Would this work?

**Comment by snoyberg** [comment]
Looks OK, though I have to admit I know nothing about `MonadAccum`. Can you update the cabal file and changelog to reflect this?

**Comment by Futarimiti** [comment]
It's something similar to `MonadWriter` but in addition you can view the accumulation real-time. It was added to mtl since 2.3. I find this occasionally useful, therefore making the instances.

Changelog updated. I don't see a cabal file here; if you meant `package.yaml` then I'm not really sure what exactly to modify? My apologies

**Comment by snoyberg** [comment]
Sorry, I meant package.yaml. And the change needed is to bump the version number. The same change needs to be made to the changelog entry and the `@since` comments, since the new version of the package needs to be 0.3.41.

**Review by snoyberg — APPROVED** [review]

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
